export const GET_CATEGORIES_PENDING = 'GET_CATEGORIES_PENDING';
export const GET_CATEGORIES_SUCCESS = 'GET_CATEGORIES_SUCCESS';
export const GET_CATEGORIES_ERROR = 'GET_CATEGORIES_ERROR';

export const GET_NEW_ARRIVALS_PENDING = 'GET_NEW_ARRIVALS_PENDING';
export const GET_NEW_ARRIVALS_SUCCESS = 'GET_NEW_ARRIVALS_SUCCESS';
export const GET_NEW_ARRIVALS_ERROR = 'GET_NEW_ARRIVALS_ERROR';

export const GET_TOP_DEALS_PENDING = 'GET_TOP_DEALS_PENDING';
export const GET_TOP_DEALS_SUCCESS = 'GET_TOP_DEALS_SUCCESS';
export const GET_TOP_DEALS_ERROR = 'GET_TOP_DEALS_ERROR';

export const GET_RECOMMENDED_PENDING = 'GET_RECOMMENDED_PENDING';
export const GET_RECOMMENDED_SUCCESS = 'GET_RECOMMENDED_SUCCESS';
export const GET_RECOMMENDED_ERROR = 'GET_RECOMMENDED_ERROR';

export const GET_MORE_TO_LOVE_PENDING = 'GET_MORE_TO_LOVE_PENDING';
export const GET_MORE_TO_LOVE_SUCCESS = 'GET_MORE_TO_LOVE_SUCCESS';
export const GET_MORE_TO_LOVE_ERROR = 'GET_MORE_TO_LOVE_ERROR';

export const TOGGLE_PROFILE_HIDDEN = "TOGGLE_PROFILE_HIDDEN";

export const GET_SEARCH_WORD = "GET_SEARCH_WORD";

export const GET_FILTERED_DATA = "GET_FILTERED_DATA";

